name: crypto_app
description: Beautiful Crypto App UI with support for dark and light mode. Created by Martin Gogolowicz.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  unicons: ^2.1.0
  get: ^4.6.1
  sizer: ^2.0.15
  crypto_font_icons: ^1.0.1
  fl_chart: ^0.45.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sobGOGlight.png
    - assets/sobGOGdark.png
